### ISSUE TITLE
some issue and need help

### ISSUE THREAD

**Issue by ERS-Long** [vojvod/CMV_addWMSLayer_Widget#1]
Hi, 

I tried your widget, and it wont add the layer for me, but it does pull down the legend.

my url to test is 

```
      var wmsLayer1 = new WMSLayer("http://services.ogc.noaa.gov/geoserver/nhc/wms?", {
        format: "png",
        visibleLayers: [0,1,2,3,4]
      });
```

this works in 

http://developers.arcgis.com/javascript/sandbox/sandbox.html?sample=layers_wms

(just plug in the layer setting).

The error I got it from using the widget in CMV is 

loadError: Error: GetCapabilities request for http://services.ogc.noaa.gov/geoserver/nhc/wms failed. (Response is null.) at Error (native) at l._parseCapabilities (http://js.arcgis.com/3.14/esri/layers/WMSLayer.js:22:525) at Object.g.hitch (http://js.arcgis.com/3.14/init.js:167:296) at http://js.arcgis.com/3.14/init.js:908:283 at c (http://js.arcgis.com/3.14/init.js:66:221) at d (http://js.arcgis.com/3.14/init.js:66:10) at b.Deferred.a.resolve.callback (http://js.arcgis.com/3.14/init.js:67:350) at c (http://js.arcgis.com/3.14/init.js:66:436) at d (http://js.arcgis.com/3.14/init.js:66:10) at b.Deferred.a.resolve.callback (http://js.arcgis.com/3.14/init.js:67:350)
message: "GetCapabilities request for http://services.ogc.noaa.gov/geoserver/nhc/wms failed. (Response is null.)"

Please let me know if you know anything.

Thanks a lot.

**Comment by vojvod** [comment]
Hi,

you have to use the names of the layers (nhc_forecast_cone,nhc_forecast_points,nhc_forecast_track)

You can get them from http://services.ogc.noaa.gov/geoserver/nhc/wms?service=wms&version=1.3.0&request=GetCapabilities

![2015-09-11_16-24-28](https://cloud.githubusercontent.com/assets/3162675/9816131/b8de93d8-58a3-11e5-9500-d035b1def1ae.png)

**Comment by ERS-Long** [comment]
Hi,

Thank you very much, yes, i did use the layer name,  but i still can bring in the map, i got the legend info with no problem. Do you think it could be projection issue?

**Comment by vojvod** [comment]
I tested the wms in CMS, as you can see in above img, and it worked ok.

Maybe, if the wms doesn't support the projection system of your map.

**Comment by vojvod** [comment]
Or maybe you have not set the proxy...

**Comment by ERS-Long** [comment]
I did set the proxy, otherwise, I will get different error. Thanks a lot.
